### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by 9acca9** [Ernisius/Picochess-NonDGT_PI#1]
Hi. Can you please post me a link to the diagram wiring???  i dont find this.
Thanks!
(i read your comment on http://chess.fortherapy.co.uk and cant find the diagram).

**Comment by Ernisius** [comment]
The wiring diagram is in fritzing format (download free fritzing program)
Is called Chessboard.fzz and is in the ChesboardLarge Folder
